### PR TITLE
[#33] Split the 'ToolCheckResult' constructor

### LINKED ISSUE #33: Split errors in Tool check
Currently, the `checkTool` function has the following type:

```haskell
checkTool :: cmd -> Tool cmd -> IO ToolCheckResult
```

where `ToolCheckResult` is defined as follows:

```haskell
data ToolCheckResult
    = ToolNotFound Text
    | ToolWrongVersion Text
    | ToolOk
```

A value of `ToolCheckResult` is thrown as an exception here:

https://github.com/chshersh/iris/blob/6be65d46a5b3f2cabd09dedbc88045c4be4fb224/src/Iris/Env.hs#L138-L141

This is suboptimal because the result can never have the `ToolOk` constructors but we're forcing downstream users to handle this case.

So we want to split success and error cases in the `ToolCheckResult` type.

### PR DESCRIPTION
**Pull request by charrsky**
Might have slipped up with denoting versions in the comments -- will be glad to hear remarks!

### CODE REVIEW

File: src/Iris/Tool.hs [hunk 1]
```diff
@@ -82,24 +83,38 @@ defaultToolSelector = ToolSelector
 data ToolCheckResult
     {- |
 
+    @since 0.0.0.1
```
Comment (chshersh) [inline src/Iris/Tool.hs:86]: I prefer to use `@since x.x.x.x` for new unreleased changes. I'll update CONTRIBUTING guide, mentioning this workflow. But the motivation is that the new version is not known at the moment of introducing new change. So we can write `x.x.x.x` and later replace all such places with a single shell command.

```suggestion
    @since x.x.x.x
```

In this case, it's a breaking change, so the new Iris version already will be `0.1.0.0`. Still, it's better to follow some practices 😌

**Review by chshersh — CHANGES_REQUESTED** [review]
That's a great start 👏🏻 

Let's also change the definition of `CliEnvError` to store `ToolCheckError` inside instead of `ToolCheckResult`:

https://github.com/chshersh/iris/blob/e352b652043f5f8f7cb5b953fdf562d267a8ff09/src/Iris/Env.hs#L121-L123

**Review by chshersh — APPROVED** [review]
Thanks, looks great! 👍🏻
